dataset_path: s3://mlperf/resnet50/data/imagenet/train
train_image_size: 224
crop_min: 0.08
batch_size: 32
train_num_workers: 16

eval_path: s3://mlperf/resnet50/data/imagenet/val
eval_image_size: 224
eval_batch_size: 64
eval_interval: 4
eval_num_workers: 12

backbone: resnet50
class_num: 1001
conv_init_mode: truncnorm
bn_init_mode: conv_bn_init

lr_decay_mode: poly
lr_max: 24.952061
lr_min: 0.0001
max_epoch: 56
warmup_epochs: 8

momentum: 0.933205
weight_decay: 0.0001
use_lars: 1
lars_epsilon: 0.0
lars_coefficient: 0.001

loss_scale: 1024
use_label_smooth: 1
label_smooth_factor: 0.1
